name: Publish Package to npmjs
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - run: echo LIB_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'v' -f 1 | rev ) >> ${GITHUB_ENV}
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm version ${{ env.LIB_VERSION }} --no-git-tag-version
      - run: npm install
      - run: npx tsc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}